# Site
name: "Orson De Witt"
title: "Orson De Witt"
description: 'The website of the developer of Egypt: Shattered Order and the author of Orca Hunting School.'
logo: 'assets/images/logo.png'
logo-orangered: 'assets/images/logo-lightblue.png'
logo-small: 'assets/images/logo-small.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /posts/:title/

games: 'https://egypt.orcinusgames.com'
# discord_invite: 'https://discord.gg/amMNE4x'
# steam_creator_page: 'https://store.steampowered.com/developer/orcinusgames/'
# youtube: 'https://www.youtube.com/channel/UCdod8Lkks-QqSjm0epIHv-A'
email: 'author@orsondewitt.com'

# Authors
authors:
  Orson:
    name: Orson
    display_name: Orson
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: author@orsondewitt.com
    twitter: https://twitter.com/OrsonDeWitt
    description: "Description"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
